name: Build and Release Binaries

on:
  push:
    branches:
      - '**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Upgrade pip and install Nuitka
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Clean and build with Nuitka
        run: |
          rm -rf build || true
          mkdir -p build
          for f in src/*.py; do
            base=$(basename "$f" .py)
            nuitka --onefile --output-dir=build --output-filename=$base "$f"
          done
          cd build
          zip release.zip $(find . -maxdepth 1 -type f ! -name "*.*" -executable)

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.ref_name }}-${{ github.sha }}
          name: Release ${{ github.ref_name }} @ ${{ github.sha }}
          files: build/release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
