name: Build and Release Binaries on Commit

on:
  push:
    branches:
      - '**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Upgrade pip and install Nuitka
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Show Nuitka version
        run: nuitka --version

      - name: Clean previous build artifacts
        run: |
          rm -rf build release.zip || true

      - name: Create build directory
        run: mkdir -p build

      - name: Compile all Python files in src/ with Nuitka
        run: |
          set -e
          for f in src/*.py; do
            echo "Compiling $f..."
            nuitka --onefile --output-dir=build "$f"
          done

      - name: List build directory contents
        run: |
          echo "Contents of build directory:"
          ls -lh build

      - name: Zip compiled binaries
        run: |
          cd build
          zip -r ../release.zip .
          cd ..
          echo "Created release.zip with contents:"
          unzip -l release.zip

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
